"""pressure-flat-band-tbg-gaia -- Gaia package from LKM evidence chains.

Generated by lkm-to-gaia.

Search query: narrow target supplied: gcn_105d2fc961f949b6
Root claims: gcn_105d2fc961f949b6
"""

from .paper_ge2021 import *
from .cross_paper import *

__all__ = [
    "gcn_105d2fc961f949b6",
]
