"""twisted-few-layer-graphite-gaia -- Gaia package from selected LKM evidence.

Generated by lkm-to-gaia style mapping. The chain backbone is copied from the
selected root evidence JSON; reviewer priors live in priors.py.

Root claim: gcn_f23eff9c755840f2
"""
from .paper_ma2020 import *
from .cross_paper import *

__all__ = [
    "gcn_f23eff9c755840f2",
]
