"""tbg-dft-relaxation-gaia -- LKM-backed Gaia package.

Generated by lkm-to-gaia from selected Turn-2 root evidence.
Root claim: gcn_de1d329f326f4e75.
"""

from .paper_cantele2020 import *
from .cross_paper import *

__all__ = [
    "gcn_de1d329f326f4e75",
]
