"""hbn-aligned-tbg-gaia -- LKM-derived Gaia subgraph.

Generated by lkm-to-gaia from the selected chain-backed root claim
gcn_584669e24c6145a7.
"""

from .paper_zhang2019 import *
from .cross_paper import *

__all__ = [
    "gcn_584669e24c6145a7",
]
