"""ma-tbg-superconducting-dome-gaia -- LKM-derived Gaia subgraph.

Generated by lkm-to-gaia from the selected chain-backed root claim
gcn_006f88d8df3548fa.
"""

from .paper_cao2018 import *
from .cross_paper import *

__all__ = [
    "gcn_006f88d8_ma_tbg_superconducting_domes",
]
